name: Docker Image CI

on:
  push:
    branches: [ "asterisk18" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag TimAEllis/asterisk-freepbx-arm:18.15-alpha
